name: plastchem
channels:
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - conda-forge::rdkit=2026.03.5
  - ipykernel=7.3.0
  - matplotlib=3.11.0
  - pandas=3.0.3
  - scikit-learn=1.9.0
  - imbalanced-learn=0.14.2
  